### ISSUE TITLE
Color contrast description

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#11]
On darker background sites the default description lettering is a bit dark... 

http://www.audiosermon.net/index.php/a/preacher/keith-daniel

**Comment by Llewellynvdm** [comment]
The component itself does not add any style (it can implement the [uikit](http://getuikit.com/) library, look in the global options of the component in the back-end). But your site template will mostly be responsible for the color of your headers. So if you want to change the colors you should do it in your template :)

You can use [firebug](http://getfirebug.com/) to see what html tag is being used on the title. Since if you know it is an h3 tag that is used, you can update the colors of you h3 tags in your template to better work with your background color.

Hope this helps, let me know if you feel that my answer is still not solving your problem.

**Comment by roybinhood** [comment]
I changed the color of all article main wording to white , but this is not the same as description default css ?

**Comment by Llewellynvdm** [comment]
You mean you changed it with in-line styles?
