### ISSUE TITLE
Language File 

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#13]
Question Does this component have a language file we can translate or to override English wording on multi language site ?

**Comment by Llewellynvdm** [comment]
Yes, you can help with this, here are the links to the files. As you finish with them please let me know and I will add them to the component for all to use.

[Back-end files](https://github.com/SermonDistributor/Joomla-3-Component/tree/master/admin/language/en-GB)
[Front-end files](https://github.com/SermonDistributor/Joomla-3-Component/tree/master/site/language/en-GB)

**Comment by roybinhood** [comment]
Thanks i.e. when done with Afrikaans ?

**Comment by roybinhood** [comment]
Is there a reason for this being closed. Is it wrong for me to translate them ? I mean some technical reason I shouldn't ?

**Comment by Llewellynvdm** [comment]
No please do and once you have it ready make a pull request or email me the files :)

Would you like to keep the issue open as a reminder?

We close issues because the initial question was answered or the code needed was committed to the repository. I felt like your question was answered and that you will let me know once you were done.

**Comment by roybinhood** [comment]
I am planning to do that simultaneously when I use that script you have to transfer the Afrikaans Site audio section to Sermon Distributer. But i am just waiting to experiment more with it one one site till bugs are fixed and a few enhancements come in future. I am doing this to lesson work and not be working on three sites at once fixing things... I am looking forward to it being on our other two main sites one day :-) and have ideas for this site www.audiosermon.net ... I will not need a reminder then , but I will need the files, but I can always ask you.

**Comment by roybinhood** [comment]
I have one question though... Do language files change

I once translated a language file and when the software dynamically updated it deleted my work or my work did not work as there were new lines to be translated

**Comment by Llewellynvdm** [comment]
I have given you the links to the files and they are in one of the above comments. Yes they  do change as we add more stuff to the component mer strings gets added and some even change. Here is a like tot the history of one of these files so you can see how often they change 

https://github.com/SermonDistributor/Joomla-3-Component/commits/master/site/language/en-GB

Once we add the files to the repo they will also show up in the folders and could be translated right here in github.

**Comment by roybinhood** [comment]
Okay but my one question is when they get updated do you have to start again or only stranslate a few lines

**Comment by roybinhood** [comment]
Sorry for all questions

**Comment by Llewellynvdm** [comment]
I only provide the English version, you will then take that and translate it. Have you looked at one of those files?

You will see that there is two sides to each string, like so: 
~~~
COM_SERMONDISTRIBUTOR="Sermon Distributor"
~~~
What will never change is the **COM_SERMONDISTRIBUTOR** part of that string since it is used all over the code base in that form. You will then in the Afrikaans file update the left side to Afrikaans.

Now when the system builds this file it sorts the strings alphabetically as you can see here:
https://github.com/SermonDistributor/Joomla-3-Component/blob/master/admin/language/en-GB/en-GB.com_sermondistributor.ini

If new strings are added you will not see them being added at the bottom of the long list but sorted into the alphabetical list. So in truth you will only need to update the strings added, but you would still need to identify them and then add them to your Afrikaans translation.

This can all be done here in github as I said, and once it is updated here where ever this component is installed it will have the Afrikaans translation available.

The questions are not a problem, you are welcome!

**Comment by Llewellynvdm** [comment]
Just remember that whatever looks like code or html must never be changed by those who translate the strings.

**Comment by roybinhood** [comment]
"in truth you will only need to update the strings added, but you would still need to identify them and then add them to your Afrikaans translation."

Okay I get it . This is what I struggled with doing the hwdmediashare translation etc ... but I see your answer is wise ... Basically although the main software files updats I can look at what has changed on that other url you sent and just identify where to add to the afrikaans translation, but ... every time I update Sermon Distributer my translation file on my site will be back to English and I will have to replace it with the updated one in cpanel etc

**Comment by Llewellynvdm** [comment]
No... that is not it.

Each language has its own folder. How the file ends-up on your server is my problem, since I add it to this repository and when you select Afrikaans as the website front-end language Sermon Distributer will use the Afrikaans automatically.

I have not tried to explain how the file gets to be on your website, but how you will update it. Let me give you the steps again :)

You will download these files in these folders:

**1 Download**

[Back-end files](https://github.com/SermonDistributor/Joomla-3-Component/tree/master/admin/language/en-GB)
[Front-end files](https://github.com/SermonDistributor/Joomla-3-Component/tree/master/site/language/en-GB)

**2 Translate all string not in full caps**

**3 Give those translations to me (first time around)**

**4 Update the file as new strings are added to English version**
I will show you how this is done when we get there.

So when you run the update on your websites they will already have the latest if you helped update it here on github.

**Comment by roybinhood** [comment]
Sorry Lewellyn , I am bad at comunicating and apologise... All I meant is I wondered if your software is like other joomla components I did translations for where ... when the whole component gets updated it deletes the langauge file on the server ( replacing it with an english version) and I have to reupload the new translation.

**Comment by Llewellynvdm** [comment]
Well if you change the English files to be Afrikaans, then yes it will. But if you follow the Joomla convention of adding each language to its correct place it should just work without the needed of manually hacking anything.

**Comment by roybinhood** [comment]
That makes sense - IN other words I put the language file in the wrong place :-) I will just translate it when I do the afrikaans site later and then ask your advice once so I know for future - If you have time
