### ISSUE TITLE
Bug pagination

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#15]
I have tried this on a few computers and it seems that ... The preachers page does not want to go to page 2 or open up more than 20 when you click that option. It stays on page one... example 

http://www.audiosermon.net/sermons

The same with the sermon page list . It stays on page one when clicking on say page 5 or 7 or 3 

http://www.audiosermon.net/a/preacher/a-w-tozer

The url changes but the page remains the same ?

**Comment by Llewellynvdm** [comment]
It seems it has to do with the cache, this is not a new Joomla issue if you Google pagination problem with cache you will see it is a long coming issue. It does not seem to be resolved as yet. I will take a much closer look. If the problem is with Sermon Distributor we will find it and fix it. Give me a few days.

**Comment by roybinhood** [comment]
No problem .. I do notice my other extensions and joomla articles did not have same problem, but the truth is cache was turned off for of my other extensions anyway individually... while the site as a whole had cache turned on for the articles and of extensions etc ...

**Comment by roybinhood** [comment]
Is there a way of having a button to only turn cache off for this extension and not have to turn it off globally ?

**Comment by roybinhood** [comment]
Dear Sir Is there any answer to this issue or any ideas ?
