### ISSUE TITLE
Multiple source

### ISSUE THREAD

**Issue by roybinhood** [SermonDistributor/Joomla-3-Component#5]
Is it possible to use dropbox and a server folder on the same site as source of different speakers ?

**Comment by Llewellynvdm** [comment]
Yes this is already possible, the source of your sermons are set per sermon.

**Comment by roybinhood** [comment]
okay but can you you use both automatic upload on both at same time i.e dual automatic listing ?

**Comment by Llewellynvdm** [comment]
Yes this is also set on sermon level. If you use [Dropbox](https://www.dropbox.com/) automatic listing it will make sure that all files in the automatic [Dropbox](https://www.dropbox.com/) is listed on your website. It will not effect files that are not set to be listed in this way, so local and manual [Dropbox](https://www.dropbox.com/) files are not affected by the auto [Dropbox](https://www.dropbox.com/) feature. What you will need to insure is that the automatic [Dropbox](https://www.dropbox.com/) does not contain the same files with the same names and under the same preacher and/or same series as set by the local and manual features. Note there is also an URL linking option.

Looking at [loudvoice](http://www.loudvoice.org/preachers) as the example it gets its files from a local-files, manual-dropbox and auto-dropbox all working at the same time since these settings are set on the sermon level and not at a global level making it extremely adjustable to your desire.
